spring:
  application:
    name: app-spring
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:teste;DB_CLOSE_ON_EXIT
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
